In [ ]:
# Perform the following operations using Python on the Telecom_Churn
# dataset. Compute and display summary statistics for each feature available
# in the dataset using separate commands for each statistic. (e.g. minimum
# value, maximum value, mean, range, standard deviation, variance and
# percentiles).

In [ ]:
import numpy as np
from scipy.stats import iqr
import pandas as pd

In [ ]:
data = pd.read_csv("Dataset/telecom_churn.csv")

In [ ]:
print(data.shape)

(3333, 21)

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB
None

In [ ]:
data

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

In [ ]:
data.min()

state                           AK
account length                   1
area code                      408
phone number              327-1058
international plan              no
voice mail plan                 no
number vmail messages            0
total day minutes              0.0
total day calls                  0
total day charge               0.0
total eve minutes              0.0
total eve calls                  0
total eve charge               0.0
total night minutes           23.2
total night calls               33
total night charge            1.04
total intl minutes             0.0
total intl calls                 0
total intl charge              0.0
customer service calls           0
churn                        False
dtype: object

In [ ]:
data.max()

state                           WY
account length                 243
area code                      510
phone number              422-9964
international plan             yes
voice mail plan                yes
number vmail messages           51
total day minutes            350.8
total day calls                165
total day charge             59.64
total eve minutes            363.7
total eve calls                170
total eve charge             30.91
total night minutes          395.0
total night calls              175
total night charge           17.77
total intl minutes            20.0
total intl calls                20
total intl charge              5.4
customer service calls           9
churn                         True
dtype: object

In [ ]:
#mean value of all attribute
data.mean()

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\2280842988.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.mean()

account length            101.064806
area code                 437.182418
number vmail messages       8.099010
total day minutes         179.775098
total day calls           100.435644
total day charge           30.562307
total eve minutes         200.980348
total eve calls           100.114311
total eve charge           17.083540
total night minutes       200.872037
total night calls         100.107711
total night charge          9.039325
total intl minutes         10.237294
total intl calls            4.479448
total intl charge           2.764581
customer service calls      1.562856
churn                       0.144914
dtype: float64

In [ ]:
#mean value of individual attribite for coluumn
data.loc[:,'account length'].mean()

101.06480648064806

In [ ]:
#mean value for first five lines
data.mean(axis = 1)[0:5]

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\260764848.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.mean(axis = 1)[0:5]

0    97.927059
1    92.084706
2    87.452353
3    81.211765
4    83.299412
dtype: float64

In [ ]:
#median value of all attribute
data.median()

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\2267780363.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.median()

account length            101.00
area code                 415.00
number vmail messages       0.00
total day minutes         179.40
total day calls           101.00
total day charge           30.50
total eve minutes         201.40
total eve calls           100.00
total eve charge           17.12
total night minutes       201.20
total night calls         100.00
total night charge          9.05
total intl minutes         10.30
total intl calls            4.00
total intl charge           2.78
customer service calls      1.00
churn                       0.00
dtype: float64

In [ ]:
data.loc[:, 'area code'].median()

415.0

In [ ]:
data.median(axis=1)[0:5]

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\1617467066.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.median(axis=1)[0:5]

0    45.07
1    27.47
2    41.38
3    50.90
4    28.34
dtype: float64

In [ ]:
data.mode()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,WV,105.0,415.0,327-1058,no,no,0.0,154.0,102.0,26.18,...,105.0,14.25,188.2,105.0,9.45,10.0,3.0,2.7,1.0,False
1,NaN,NaN,NaN,327-1319,NaN,NaN,NaN,159.5,NaN,27.12,...,NaN,16.12,191.4,NaN,9.66,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,327-3053,NaN,NaN,NaN,174.5,NaN,29.67,...,NaN,NaN,197.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,327-3587,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,210.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,327-3850,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,214.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,NaN,NaN,NaN,422-7728,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3329,NaN,NaN,NaN,422-8268,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3330,NaN,NaN,NaN,422-8333,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3331,NaN,NaN,NaN,422-8344,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3332,NaN,NaN,NaN,422-9964,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.std()

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\2723740006.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.std()

account length            39.822106
area code                 42.371290
number vmail messages     13.688365
total day minutes         54.467389
total day calls           20.069084
total day charge           9.259435
total eve minutes         50.713844
total eve calls           19.922625
total eve charge           4.310668
total night minutes       50.573847
total night calls         19.568609
total night charge         2.275873
total intl minutes         2.791840
total intl calls           2.461214
total intl charge          0.753773
customer service calls     1.315491
churn                      0.352067
dtype: float64

In [ ]:
data.std(axis = 0)[1:5]

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\1211571569.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.std(axis = 0)[1:5]

area code                42.371290
number vmail messages    13.688365
total day minutes        54.467389
total day calls          20.069084
dtype: float64

In [ ]:
print(data.loc[:,'area code'].std())

42.371290485606615

In [ ]:
data.var()

C:\Users\PRATIK RATHOD\AppData\Local\Temp\ipykernel_5988\445316826.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.var()

account length            1585.800121
area code                 1795.326257
number vmail messages      187.371347
total day minutes         2966.696487
total day calls            402.768141
total day charge            85.737128
total eve minutes         2571.894016
total eve calls            396.910999
total eve charge            18.581856
total night minutes       2557.714002
total night calls          382.930472
total night charge           5.179597
total intl minutes           7.794368
total intl calls             6.057576
total intl charge            0.568173
customer service calls       1.730517
churn                        0.123951
dtype: float64

In [ ]:
#Interquartile Range (IQR)
# The Interquartile Range (IQR) is a measure of statistical dispersion, and is calculated as the difference 
# between the upper quartile (75th percentile) and the lower quartile (25th percentile).
iqr(data['area code'])

102.0